// <auto-generated />
namespace SQLModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Roy_Add_BaseModel20161226 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Roy_Add_BaseModel20161226));
        
        string IMigrationMetadata.Id
        {
            get { return "201612261034360_Roy_Add_BaseModel20161226"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
