// <auto-generated />
namespace SQLModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Roy_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Roy_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201612210744266_Roy_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
